export {default as Analytics} from './components/pages/Analytics'
export {default as Classes} from './components/pages/Classes'
export {default as Profile} from './components/pages/Profile'
export {default as Error} from './components/pages/404'
export {default as LoginSignin} from './components/pages/LoginSignin'
export {default as Students} from './components/pages/Etudiants'
export {default as Examens} from './components/pages/Examens'
export {default as EditerExamen} from './components/pages/EditerExamen'
export {default as VerifyEmail} from './components/pages/verifyEmail'
export {default as PasserExamenPage} from './components/pages/PasserExamenPage'
export {default as Home} from './components/pages/home'
export {default as Subscrib} from './components/pages/Subscrib'
export {default as ForgotPassword} from './components/pages/forgotPassword'
export {default as ResetPassword} from './components/pages/resetPassword'
export {default as StudentDashboard} from './components/pages/studentDashboard'
export {default as ResultOffQuiz} from './components/pages/ResultOffQuiz'


