name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Set up backend
      run: |
        cd Backend
        npm install
        npm run serve
    - name: Set up frontend
      run: |
        cd Frontend
        npm install
        npm run start
    - name: Run tests
      run: |
        cd backend
        npm test
